"""empty message

Revision ID: 0d5bc779d8e8
Revises: 990cb29a6a7a
Create Date: 2025-02-18 21:10:59.209996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5bc779d8e8'
down_revision = '990cb29a6a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(), nullable=False))
        batch_op.drop_column('descrição')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrição', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
