"""empty message

Revision ID: 12ca34a5f6e3
Revises: 7fd23ae91d9b
Create Date: 2025-02-19 13:02:36.943524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ca34a5f6e3'
down_revision = '7fd23ae91d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos', sa.Enum(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('produtos')

    # ### end Alembic commands ###
